### PR TITLE
Cherrypick #2455 to 2.7.3

### PR DESCRIPTION
**Pull request by caalador**
Part of #17326

### CODE REVIEW

**Comment by mshabarov** [comment]
Two comments:
- should it go to `2.7.4` branch?
- https://github.com/vaadin/atmosphere/pull/10 seems to have more changes, do you have any idea why?

**Comment by caalador** [comment]
I actually can't say how this is handled.
On the #10 I see that the 4 first compatibility commits are the same as what is contained in bb90602 here so I guess they have been copied in parts and manually committed?

**Comment by caalador** [comment]
Created new branch 2.7.4 from 2.7.3 and targeted PR to it.

**Review by mshabarov — CHANGES_REQUESTED** [review]
The picked changes look the same as in the original fix, LGTM.
We discussed internally with @Artur- how usually we do the versioning.
This patch is still based in `2.7.3`, so I think it should target `2.7.3` branch and later after merge we will release next `2.7.3` with incremented vaadin version, i.e. `2.7.3.slf4jvaadin5`.
So could you please @caalador change back to `2.7.3`? Sorry for confusion.

**Review by mshabarov — APPROVED** [review]

**Pull request merged**
